FROM rocker/r-ubuntu:18.04
MAINTAINER Christopher Peterson Christopher.R.Peterson@gmail.com

# prevent interactive apt stuff

# so whats going on here:
# install V8 and TBB dependencies
# Install a bunch of packages
# Install up to date StanHeaders and rstan from source using scripts from here:
  # https://discourse.mc-stan.org/t/rstan-and-stan-2-20-0/13486/3
# Install remaining R packages from source
 # apt-get install -y --no-install-recommends \
#    software-properties-common && \

RUN \
  apt-get update && \
  apt-get install -y --no-install-recommends  \
    git \
    libv8-dev \
    libtbb-dev \
    r-cran-rcpp \
    r-cran-rcppparallel \
    r-cran-rcppeigen \
    r-cran-inline \
    r-cran-devtools \
    r-cran-bh \
    r-cran-kernsmooth \
    r-cran-tidyverse \
    r-cran-loo \
    r-cran-bayesplot \
    r-cran-rstantools \
    r-cran-shinystan \
    libcurl4-openssl-dev 

RUN \
  Rscript -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/StanHeaders/StanHeaders_2.21.0-1.tar.gz", repos = NULL)' && \
  Rscript -e 'remotes::install_github("stan-dev/rstan", ref = "develop", subdir = "rstan/rstan", upgrade = "never")' && \
  install2.r --error  \
    rstanarm \
    brms \
    projpred \
    tidybayes \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

# Config for rstudio user
RUN mkdir -p /home/rstudio/.R/ \
#    && echo "\nCXX=g++ -ftemplate-depth-256\n" >> /home/rstudio/.R/Makevars \
#    && echo "CC=g++\n" >> /home/rstudio/.R/Makevars \
&& echo "CXXFLAGS=-O3\n" >> /home/rstudio/.R/Makevars \
&& echo "\nrstan::rstan_options(auto_write = TRUE)" >> /home/rstudio/.Rprofile \
&& echo "options(mc.cores = parallel::detectCores())" >> /home/rstudio/.Rprofile
